# Macro used to run the ARAPUCA simulation.
#
# Now we define the source. Right now it is a mono-energetic beam of muons+
# We can set either energy or momentum, 
# but not both (since the mass is already defined).
# Between energy and momentum, geant4 will follow the last instruction before beamOn.

/gun/particle opticalphoton
/gun/energy 2.5 eV
/gun/polarization 1 1 1
/gun/position -0.3 0.5 0 m
/gun/direction 1. -1.5 0
/run/beamOn 1